### ISSUE TITLE
Idea - also set a threshold for steps

### ISSUE THREAD

**Issue by asgrim** [Brunty/behat-speedtrap#5]
Nice idea, gonna add this to a test suite tomorrow I'm performance enhancing.

A nice addition would be to (optionally) also set an individual step threshold to see which step(s) are slowest to pinpoint.

Note; I only read the readme so far, I didn't use it yet so maybe you already did this, if so please close and forgive me!

**Comment by Brunty** [comment]
That could be done, it doesn't exist at the minute but shouldn't be difficult to add at a global level across the whole suite (I'm looking at per-scenario thresholds soon too)

**Comment by asgrim** [comment]
If I can get a chance today I'll see if I can PR it in :)

**Comment by Brunty** [comment]
❤️

**Comment by Brunty** [comment]
Fixed by #6
